apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: base
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 7.10.1
    chart: elasticsearch
    helm:
      parameters:
        - name: "persistence.enabled"
          value: "false"
        - name: "resources.requests.cpu"
          value: "2000m"
        - name: "resources.requests.memory"
          value: "12Gi"          
        - name: "resources.limits.cpu"
          value: "2000m"
        - name: "resources.limits.memory"
          value: "12Gi"
        - name: "esJavaOpts"
          value: "-Xmx6g -Xms6g"
        - name: "replicas"
          values: "1"
        - name: "minimumMasterNodes"
          value: "1"               


  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:     
    - Validate=false 
    - CreateNamespace=false 
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas