apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: base
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 7.10.1
    chart: kibana
    helm:
      parameters:
        - name: "service.type"
          value: "LoadBalancer"
        - name: "service.port"
          value: "80"          

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true 
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas