apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loft
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: base
  source:
    repoURL: https://charts.devspace.sh
    targetRevision: 1.4.1
    chart: loft
    helm:
      parameters:
        - name: "admin.password"
          value: "vx#%g@^q9e2&4vgk"
        - name: "ingress.enabled"
          value: "false"          
        - name: "service.type"
          value: "LoadBalancer"
        - name: "certIssuer.create"
          value: "false"   


  destination:
    server: https://kubernetes.default.svc
    namespace: loft
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true 
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas