apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: base
  source:
    repoURL: https://shipa-charts.storage.googleapis.com
    targetRevision: 1.1.1
    chart: shipa
    helm:
      parameters:
      - name: "auth.adminUser"
        value: "admin"

      - name: "auth.adminPassword"
        value: "0*u!q1@c6s7$fc7$"
        
  destination:
    server: https://kubernetes.default.svc
    namespace: shipa-system
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true 
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas