apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-group-infra
spec:
  order: 30
  ingress:
  - action: Allow
    source:
      namespaceSelector: source.group.netpolicy.hypermachines.net/infra == 'true'
        