apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-within-ns
spec:
  podSelector:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            source.ns.netpolicy.hypermachines.net/daas-{{ .Values.project.key }}: "true" 