apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-ingress-group-infra
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          source.group.netpolicy.hypermachines.net/infra: "true"