apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-within-ns
spec:
  ingress:
  - action: Allow
    source:
      namespaceSelector: source.ns.netpolicy.hypermachines.net/daas-{{ .Values.project.key }} == 'true'
                  