apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-linkerd
spec:
  order: 20
  selector: all()
  ingress:
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: slinkerd.io/control-plane-ns == 'linkerd'
                  