apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-within-ns
spec:
  podSelector:
  ingress:
  - from:
    - NamespaceSelector:
        matchLabels:
          name: "daas-{{ .Values.project.key }}"