kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "daas-{{ .Values.project.key }}-role"
  namespace: "daas-{{ .Values.project.key }}"
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "list", "watch"]