
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glusterfs-kadalu-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tomasliumparas/argocd-demo.git
    targetRevision: HEAD
    path: applications/glusterfs-kadalu-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: kadalu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true