apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd2
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 2.8.0
    helm:
      parameters:
      - name: global.identityTrustAnchorsPEM
        value: |
          -----BEGIN CERTIFICATE-----
          MIIBlDCCATugAwIBAgIQVosZqEikp4bzcA9hFx1cTDAKBggqhkjOPQQDAjApMScw
          JQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjAxMjA3
          MjAxNzU3WhcNMzAxMjA1MjAxNzU3WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5r
          ZXJkLmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARHhhsR
          7/nnjZL7qp7DrKm9hC07Ametf+J1fdocuFPt7Xqzk9/RiXRIMl7RP4PYCsr4F8Xr
          q70X2oNKlJoTBu4Zo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB
          /wIBATAdBgNVHQ4EFgQUCBFw8fHYa3NPKUWJmM4x7lSGYDUwCgYIKoZIzj0EAwID
          RwAwRAIgOMdgnB931/xlolmUR4UMJ5VAFJKx8IvlUgCrlHzqRXcCIFfUqc+KRJ5P
          7KpjOiSSbvIKzlXDnube1M58KKfvuT7M
          -----END CERTIFICATE-----
      - name: identity.issuer.tls.crtPEM
        value: |
          -----BEGIN CERTIFICATE-----
          MIIBlzCCATygAwIBAgIRAMrcrlDoVgLsdPat63OFkPMwCgYIKoZIzj0EAwIwKTEn
          MCUGA1UEAxMeaWRlbnRpdHkubGlua2VyZC5jbHVzdGVyLmxvY2FsMB4XDTIwMTIw
          NzIwMTgxNFoXDTIxMTIwNzIwMTgxNFowKTEnMCUGA1UEAxMeaWRlbnRpdHkubGlu
          a2VyZC5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBSeL
          yUkBp1AKJp6KRpaxlN+2qorYjvcmreRGDpRwNiKTXSD56tYGxXlo56CuMz5eS0j5
          9Yl0fkWbbdZSPTglSqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYB
          Af8CAQAwHQYDVR0OBBYEFJlPCvhpvHJzVcUIJPW3rfp4szfxMAoGCCqGSM49BAMC
          A0kAMEYCIQDM5mtN8wqUorZbEvscSAUOvFZT1H/8V7b3hPaTB7sWlAIhAJhj/BMt
          OxYEtCyfC9AyGYUe7jo6IEoRiM5lWMRD8R2/
          -----END CERTIFICATE-----
      - name: identity.issuer.tls.keyPEM
        value: |
          -----BEGIN EC PRIVATE KEY-----
          MHcCAQEEIBwJ1vj3nmpCB817F+BfNy8XlI19IxFgPmF11uCozFgkoAoGCCqGSM49
          AwEHoUQDQgAEBSeLyUkBp1AKJp6KRpaxlN+2qorYjvcmreRGDpRwNiKTXSD56tYG
          xXlo56CuMz5eS0j59Yl0fkWbbdZSPTglSg==
          -----END EC PRIVATE KEY-----
      - name: identity.issuer.crtExpiry
        value: "2021-12-07T15:24:11Z"
      - name: "enforcedHostRegexp"
        value: "10.7.0.64"
      - name: installNamespace
        value: "true"
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true 
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m     

