apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd2
    repoURL: https://helm.linkerd.io/stable
    targetRevision: stable-2.9.0
    helm:
      parameters:
      - name: global.identityTrustAnchorsPEM
        value: |
          -----BEGIN CERTIFICATE-----
          MIIBlzCCATygAwIBAgIRAIB4yE9WyGk6CePYoQ0t+agwCgYIKoZIzj0EAwIwKTEn
          MCUGA1UEAxMeaWRlbnRpdHkubGlua2VyZC5jbHVzdGVyLmxvY2FsMB4XDTIwMTIw
          NzEyMzIyM1oXDTMwMTIwNTEyMzIyM1owKTEnMCUGA1UEAxMeaWRlbnRpdHkubGlu
          a2VyZC5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEimtr
          hiw3AsI2++jd66avn61xuB97r3QGGqcb4QFBTD37YFmLJU25p1R6mAeDzczmzKvV
          M0UpzkyXwCH9Hs5ZuqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYB
          Af8CAQEwHQYDVR0OBBYEFLYqfp3RRS/X2yGsbuZX8U4EM+cTMAoGCCqGSM49BAMC
          A0kAMEYCIQCwL13/JGkc/e3HRncUveP1k9lIH/Okk3dTKBLhQw3kFwIhAIQd1T1E
          Ex3pl6G+6/oX7181xZ67tH6eTfNj4CELEEnm          
          -----END CERTIFICATE-----
      - name: identity.issuer.tls.crtPEM
        value: |
          -----BEGIN CERTIFICATE-----
          MIIBlTCCATygAwIBAgIRAPWPGkS8vq62p6Xxy02ZAuQwCgYIKoZIzj0EAwIwKTEn
          MCUGA1UEAxMeaWRlbnRpdHkubGlua2VyZC5jbHVzdGVyLmxvY2FsMB4XDTIwMTIw
          NzEyMzYwM1oXDTIxMTIwNzEyMzYwM1owKTEnMCUGA1UEAxMeaWRlbnRpdHkubGlu
          a2VyZC5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3OOg
          VWcqV+cZjPVWfCvanGmTbEpnkIUSIWYQ/kl8r79FpxSMR0+HcZXuPLCpLJh6P/MQ
          GEFxo+61LTbREEjdA6NFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYB
          Af8CAQAwHQYDVR0OBBYEFK8/Y0GjXPUBVLyUEtjAcoY9nwFSMAoGCCqGSM49BAMC
          A0cAMEQCICEjwZcNW4ojbWSrh5G/i/onarj7ytwGSmZFb0W+0r8YAiBbjUFAucn+
          QtuFnt9EBd/Yvjf60BpdS6JcZxI9I5M63w==
          -----END CERTIFICATE-----    
      - name: identity.issuer.tls.keyPEM
        value: |
          -----BEGIN EC PRIVATE KEY-----
          MHcCAQEEIHJhcSPmxzfqBM8xT4mo7o7VVpDflSFfxx/HpXYVsEEGoAoGCCqGSM49
          AwEHoUQDQgAE3OOgVWcqV+cZjPVWfCvanGmTbEpnkIUSIWYQ/kl8r79FpxSMR0+H
          cZXuPLCpLJh6P/MQGEFxo+61LTbREEjdAw==
          -----END EC PRIVATE KEY-----
      - name: identity.issuer.crtExpiry
        value: "2021-12-07T15:24:11Z"
      - name: "enforcedHostRegexp"
        value: "10.7.0.63"
      - name: installNamespace
        value: "true"
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true 
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m     
  ignoreDifferences:
  - group: ""
    kind: Secret
    name:  linkerd-proxy-injector-tls
    jsonPointers:
    - /data/crt.pem
    - /data/key.pem
  - group: ""
    kind: Secret
    name:  linkerd-sp-validator-tls
    jsonPointers:
    - /data/crt.pem
    - /data/key.pem
  - group: ""
    kind: Secret
    name:  linkerd-tap-tls
    jsonPointers:
    - /data/crt.pem
    - /data/key.pem
  - group: admissionregistration.k8s.io/v1beta1
    kind: MutatingWebhookConfiguration
    name:  linkerd-proxy-injector-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io/v1beta1
    kind: ValidatingWebhookConfiguration
    name:  linkerd-sp-validator-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: apiregistration.k8s.io/v1
    kind: APIService
    name: v1alpha1.tap.linkerd.io
    jsonPointers:
    - /spec/caBundle