apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd2
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 2.8.0
    helm:
      parameters:
      - name: global.identityTrustAnchorsPEM
        value: |
          -----BEGIN CERTIFICATE-----
          MIIBlzCCATygAwIBAgIRAIB4yE9WyGk6CePYoQ0t+agwCgYIKoZIzj0EAwIwKTEn
          MCUGA1UEAxMeaWRlbnRpdHkubGlua2VyZC5jbHVzdGVyLmxvY2FsMB4XDTIwMTIw
          NzEyMzIyM1oXDTMwMTIwNTEyMzIyM1owKTEnMCUGA1UEAxMeaWRlbnRpdHkubGlu
          a2VyZC5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEimtr
          hiw3AsI2++jd66avn61xuB97r3QGGqcb4QFBTD37YFmLJU25p1R6mAeDzczmzKvV
          M0UpzkyXwCH9Hs5ZuqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYB
          Af8CAQEwHQYDVR0OBBYEFLYqfp3RRS/X2yGsbuZX8U4EM+cTMAoGCCqGSM49BAMC
          A0kAMEYCIQCwL13/JGkc/e3HRncUveP1k9lIH/Okk3dTKBLhQw3kFwIhAIQd1T1E
          Ex3pl6G+6/oX7181xZ67tH6eTfNj4CELEEnm          
          -----END CERTIFICATE-----
      - name: identity.issuer.scheme
        value: kubernetes.io/tls
      - name: installNamespace
        value: "false"
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: ""
    kind: Secret
    name:  linkerd-proxy-injector-tls
    jsonPointers:
    - /data/crt.pem
    - /data/key.pem
  - group: ""
    kind: Secret
    name:  linkerd-sp-validator-tls
    jsonPointers:
    - /data/crt.pem
    - /data/key.pem
  - group: ""
    kind: Secret
    name:  linkerd-tap-tls
    jsonPointers:
    - /data/crt.pem
    - /data/key.pem
  - group: admissionregistration.k8s.io/v1beta1
    kind: MutatingWebhookConfiguration
    name:  linkerd-proxy-injector-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io/v1beta1
    kind: ValidatingWebhookConfiguration
    name:  linkerd-sp-validator-webhook-config
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: apiregistration.k8s.io/v1
    kind: APIService
    name: v1alpha1.tap.linkerd.io
    jsonPointers:
    - /spec/caBundle