apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 9.11.0
    chart: traefik
    helm:
      parameters:
        - name: "rbac.namespaced"
          value: "false"
        - name: "service.spec.externalTrafficPolicy"
          value: Local
        - name: "ingressRoute.dashboard.enabled"
          value: "true"
        - name: "logs.access.enabled"
          value: "true"
        - name: "persistence.enabled"
          value: "true"
        - name: "persistence.existingClaim"
          value: "azure-traefikdata"
        - name: "additionalArguments[0]"
          value: "-certificatesresolvers.le.acme.storage=/data/acme.json"
        - name: "pilot.enabled"
          value: "true"
        - name: "pilot.token"
          value: "d26fa1de-86eb-492b-a870-84b976d9c67e"
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true 
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas