apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-mesh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/mesh
    targetRevision: 3.0.6
    chart: traefik-mesh
    helm:  
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-mesh
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true 
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas