
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daas-f314e
  namespace: argocd
spec:
  project: customers
  source:
    repoURL: https://github.com/tomasliumparas/argocd-demo.git
    targetRevision: HEAD
    path: apps/daas-project
    helm:
      parameters:
      - name: "project.key"
        value: "f314e"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true       