---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
 # This will be used as name of PV Hosting Volume
  name: bronze0
spec:
  type: Replica1
  storage:
    - node: snode0
      device: /dev/sdd
