apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "azure-traefikdata" 
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "3Gi" 
  storageClassName: azure-traefikdata 
  volumeName: "azure-traefikdata" 
