spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/tomasliumparas/argocd-demo.git
    targetRevision: HEAD

project:
  key: ""
  quota:
    cpu: 1
    ram: 2

dummyapp:
  namespace: ""