apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "daas-{{ .Values.project.key }}"
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: "daas-{{ .Values.project.key }}"

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  destinations:
  - server: '*'
    namespace: "daas-{{ .Values.project.key }}"
  - server: '*'
    namespace: "argocd"    