
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-app
  namespace: argocd
spec:
  project: "daas-{{ .Values.project.key }}"
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: daas-project/dummy-app
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.dummyapp.namespace }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true