apiVersion: v1
kind: Namespace
metadata:
  name: "daas-{{ .Values.project.key }}"
  annotations:
    linkerd.io/inject: enabled
  labels:
    name: "daas-{{ .Values.project.key }}"
    source.ns.netpolicy.hypermachines.net/daas-{{ .Values.project.key }}: "true"
spec:
  finalizers:
  - kubernetes
