
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-base
  namespace: argocd
spec:
  project: "daas-{{ .Values.project.key }}"
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: daas-project/project-base
    helm:
      {{- with .Values }}    
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: "daas-{{ .Values.project.key }}"
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:     
    - Validate=false 
    - CreateNamespace=false